// Copyright (C) 2026 SharpEmu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later

using System.Text;
using System.Text.Json;
using SharpEmu.HLE;
using SharpEmu.Libs.Agc;
using Xunit;

namespace SharpEmu.Libs.Tests;

/// <summary>
/// Round-trip tests over the synthetic corpus in Corpus/corpus-*.jsonl
/// (generated by tools/corpus/generate.py from LLVM tooling only — no
/// console-derived bytes). Each case is a single instruction; the tests
/// append s_endpgm and feed the raw bytes to the Gen5 decoder.
/// </summary>
public sealed class CorpusDecodeTests
{
    private const ulong CodeAddress = 0x0000_1000_0000UL;
    private const uint SEndpgmWord = 0xBF810000;

    // LLVM mnemonic (suffix-stripped) -> decoder opcode name, where the
    // mechanical normalization below does not match the decoder's naming.
    private static readonly Dictionary<string, string> NameMap =
        LoadNameMap();

    public static TheoryData<string> Targets => new() { "gfx1013", "gfx1030" };

    [Theory]
    [MemberData(nameof(Targets))]
    public void AllCorpusCasesDecode(string target)
    {
        var failures = new StringBuilder();
        var total = 0;

        foreach (var entry in LoadCases(target))
        {
            total++;
            var bytes = Convert.FromHexString(entry.Hex);
            var ctx = CreateContext(bytes);

            if (!Gen5ShaderTranslator.TryDecodeProgram(ctx, CodeAddress, out var program, out var error))
            {
                failures.AppendLine($"decode-failed: {entry.Asm} :: {error}");
                continue;
            }

            var decodedBytes = program.Instructions.Sum(i => i.Words.Count) * 4;
            if (decodedBytes != bytes.Length + 4)
            {
                failures.AppendLine(
                    $"size-mismatch: {entry.Asm} :: decoded {decodedBytes} bytes, expected {bytes.Length + 4}");
            }
        }

        WriteReport($"decode-report-{target}.txt", failures);
        Assert.True(total > 300, $"corpus for {target} is suspiciously small: {total}");
        Assert.True(failures.Length == 0, $"{target}:\n{failures}");
    }

    [Theory]
    [MemberData(nameof(Targets))]
    public void DecodedOpcodesMatchLlvmMnemonics(string target)
    {
        var mismatches = new StringBuilder();

        foreach (var entry in LoadCases(target))
        {
            var bytes = Convert.FromHexString(entry.Hex);
            var ctx = CreateContext(bytes);
            if (!Gen5ShaderTranslator.TryDecodeProgram(ctx, CodeAddress, out var program, out _)
                || program.Instructions.Count == 0)
            {
                continue; // reported by AllCorpusCasesDecode
            }

            var mnemonic = entry.Disasm.Split(' ', 2)[0];
            var expected = NameMap.TryGetValue(StripSuffix(mnemonic), out var mapped)
                ? mapped
                : Normalize(mnemonic);
            var actual = program.Instructions[0].Opcode;

            if (!string.Equals(expected, actual, StringComparison.Ordinal))
            {
                mismatches.AppendLine($"{mnemonic} -> expected '{expected}', decoder said '{actual}' ({entry.Asm})");
            }
        }

        WriteReport($"name-report-{target}.txt", mismatches);
        Assert.True(mismatches.Length == 0, $"{target}:\n{mismatches}");
    }

    private static void WriteReport(string fileName, StringBuilder content)
    {
        // Full machine-readable report next to the test binary: assertion
        // messages get truncated by the runner, this file never is.
        File.WriteAllText(Path.Combine(AppContext.BaseDirectory, fileName), content.ToString());
    }

    private static string StripSuffix(string mnemonic)
    {
        foreach (var suffix in (string[])["_e32", "_e64", "_sdwa", "_dpp"])
        {
            if (mnemonic.EndsWith(suffix, StringComparison.Ordinal))
            {
                return mnemonic[..^suffix.Length];
            }
        }

        return mnemonic;
    }

    private static string Normalize(string mnemonic)
    {
        var parts = StripSuffix(mnemonic).Split('_', StringSplitOptions.RemoveEmptyEntries);
        var builder = new StringBuilder();
        foreach (var part in parts)
        {
            builder.Append(char.ToUpperInvariant(part[0]));
            builder.Append(part.AsSpan(1));
        }

        return builder.ToString();
    }

    private static Dictionary<string, string> LoadNameMap()
    {
        var path = Path.Combine(AppContext.BaseDirectory, "Corpus", "name-map.json");
        if (!File.Exists(path))
        {
            return [];
        }

        return JsonSerializer.Deserialize<Dictionary<string, string>>(File.ReadAllText(path)) ?? [];
    }

    private static IEnumerable<CorpusCase> LoadCases(string target)
    {
        var path = Path.Combine(AppContext.BaseDirectory, "Corpus", $"corpus-{target}.jsonl");
        foreach (var line in File.ReadLines(path))
        {
            var entry = JsonSerializer.Deserialize<CorpusCase>(line, JsonOptions)!;
            if (entry.Status == "ok")
            {
                yield return entry;
            }
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
    };

    private static CpuContext CreateContext(byte[] caseBytes)
    {
        var bytes = new byte[caseBytes.Length + 4];
        caseBytes.CopyTo(bytes, 0);
        BitConverter.TryWriteBytes(bytes.AsSpan(caseBytes.Length), SEndpgmWord);

        var memory = new FakeGuestMemory();
        memory.AddRegion(CodeAddress, bytes);
        return new CpuContext(memory, Generation.Gen5);
    }

    private sealed record CorpusCase(
        string Family,
        string Asm,
        string Target,
        string Status,
        string Hex,
        string Disasm);
}
