# Copyright (C) 2026 SharpEmu Emulator Project
# SPDX-License-Identifier: GPL-2.0-or-later

name: Tests

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "**/*.md"
      - "**/*.png"
      - "**/*.jpeg"
      - "**/*.jpg"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "**/*.png"
      - "**/*.jpeg"
      - "**/*.jpg"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: tests-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'push' }}

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Test
        run: dotnet test src/SharpEmu.Libs.Tests -c Release
